name: Cron Deploy (Render)

on:
  schedule:
    - cron: '0 0 * * *' # Tous les jours à minuit UTC
  workflow_dispatch: # Permet le déclenchement manuel

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy Hook
        env:
          RENDER_DEPLOY_HOOK: "${{ secrets.RENDER_DEPLOY_HOOK }}"
        run: |
          curl -X POST "$RENDER_DEPLOY_HOOK"
